_wandb:
    value:
        cli_version: 0.23.0
        e:
            a8t5slikgvxly7chuxi6tcwcqrtw0ocr:
                args:
                    - --config_file
                    - /media/mu/zoo_vision/training/PoseGuidedReID/configs/elephant_resnet.yml
                    - --do_training
                    - --notes
                    - Elephant ReID with ResNet50 backbone, triplet + softmax loss
                    - SOLVER.IMS_PER_BATCH
                    - "32"
                    - SOLVER.MAX_EPOCHS
                    - "120"
                    - SOLVER.BASE_LR
                    - "0.1"
                    - SOLVER.STEPS
                    - (20, 40, 70)
                    - SOLVER.OPTIMIZER_NAME
                    - SGD
                    - SOLVER.CHECKPOINT_PERIOD
                    - "10"
                    - SOLVER.LOG_PERIOD
                    - "100"
                    - SOLVER.WARMUP_EPOCHS
                    - "5"
                    - MODEL.DIST_TRAIN
                    - "False"
                    - MODEL.AGG_POSE_FEATURE
                    - "False"
                    - DATALOADER.SAMPLER
                    - softmax
                    - OUTPUT_DIR
                    - /media/mu/zoo_vision/training/PoseGuidedReID/logs/elephant_resnet50
                    - TEST.MAX_RANK
                    - "20"
                    - TEST.MAP_MAX_RANK
                    - "True"
                codePath: training/PoseGuidedReID/tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1411323449344"
                        used: "864146591744"
                email: jassica.zm53@gmail.com
                executable: /media/mu/zoo_vision/training/PoseGuidedReID/venv/bin/python3
                git:
                    commit: 02380ce9fb364fee303027631a1582318cd67aec
                    remote: git@github.com:zhoumu53/zoo_vision.git
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-f690c3c4-cd51-7272-fe1f-da4c623d62fb
                host: forschung-zoo
                memory:
                    total: "67220496384"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /media/mu/zoo_vision/training/PoseGuidedReID/tools/train.py
                python: CPython 3.12.3
                root: /media/mu/zoo_vision/training/PoseGuidedReID
                startedAt: "2025-11-20T15:32:41.450844Z"
                writerId: a8t5slikgvxly7chuxi6tcwcqrtw0ocr
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 80
            "2":
                - 1
                - 41
                - 49
                - 63
                - 80
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint:
    value: /media/mu/zoo_vision/training/PoseGuidedReID/logs/elephant_resnet50/net_last.pth
config_file:
    value: /media/mu/zoo_vision/training/PoseGuidedReID/configs/elephant_resnet.yml
epochs:
    value: 120
exp_name:
    value: elephant_resnet50_train
gamma:
    value: 0.1
learning_rate:
    value: 0.1
momentum:
    value: 0.9
num_gpus:
    value:
        - 0
optimizer:
    value: SGD
output_dir:
    value: /media/mu/zoo_vision/training/PoseGuidedReID/logs/elephant_resnet50
project_name:
    value: elephant_elephant_resnet50
weight_decay:
    value: 0.0005
with_pose:
    value: false
